### ISSUE TITLE
context-blocks

### ISSUE THREAD

**Issue by AndyCapiau** [blowmage/minitest-rails-capybara#39]
I not sure if this qualifies as an 'issue':

First off, I'm grateful for this gem. I really love it! This is a really efficient way of using capybara. Genius if you ask me.

I was kinda expecting I would be able to define a context (or describe) block, but this throws errors. I then realized, it's because there are no 'context' blocks, nor can we nest things in describe blocks and features can't be nested.

Say for a feature there are two ways of doing it:

```
 scenario "an employee can make a submission" do
    run_task_a
    run_task_b
    run_task_c
    run_different_task_x
  end
  scenario "when an employee tries to submit without an amount, he should get a describing error message"
    run_task_a
    run_task_b
    run_task_c
    run_different_task_y
  end
```

 Is there a way to dry up this code and achieve something like this with this gem in it's current state?

```
context "the correct token is provided in the submission link" do
  setup do
    run_task_a
    run_task_b
    run_task_c
  end

  scenario "an employee can make a submission" do
    run_different_task_x
  end

  scenario "when an employee tries to submit without an amount, he should get a describing error message"
    run_different_task_y
  end
end
```

Unless I'm using this wrong, I really think this would make the code way more efficient.

**Comment by justuseapen** [comment]
You can define the setup method anywhere:

`
def setup
  run_task_a
  run_task_b
  run_task_c
end

scenario "an employee can make a submission" do
  setup
  run_different_task_x
end

scenario "when an employee tries to submit without an amount, he should get a describing error message"
  setup
  run_different_task_y
end
`

At least, that's what I did today when encountering the same problem. Maybe there is a better way.

**Comment by blowmage** [comment]
Apologies for not seeing this issue until now.

> I was kinda expecting I would be able to define a context (or describe) block, but this throws errors. I then realized, it's because there are no 'context' blocks, nor can we nest things in describe blocks and features can't be nested.

That doesn't seem right. While there is no `context` block defined by the Minitest Spec DSL, you are able to nest `feature` blocks. In fact, the [test/test_spec.rb](https://github.com/blowmage/minitest-rails-capybara/blob/master/test/test_spec.rb) test does just that.

All of the Minitest Spec DSL is still in play. So a `before` block, or a `setup` method, will be run before each test/`scenario` block.

**Comment by blowmage** [comment]
Closing as `context` is an RSpec Spec DSL thing, not a Capybara DSL thing. Minitest has decided not to add `context` to the Minitest Spec DSL, so I don't think we will do it here.

FWIW, its easy enough to add `context` in your own test helper:

```ruby
class Minitest::Spec
  class << self
    alias :context :describe
  end
end
```
